### ISSUE TITLE
Add workshop peripherals to BOM

### ISSUE THREAD

**Issue by rpcme** [rpcme/aws-cloud-and-xilinx-workshop#27]
@skeffinw - the BOM has the main materials, but there are a lot of peripherals and memories (cables, SD cards, etc) that are also required.  We need to get those listed as well for completeness.

**Comment by skeffinw** [comment]
The actual kits for Ultra96 and MicroZed already include SD-Cards and thus these do not need to be ordered separately.  One USB is already included in the MicroZed kit so only added one per board kit is the itemized BOM.
